[[main]]
    identifier = "home"
    name = "Home"
    pre = "<i class='fa fa-heart'></i>"
    url = "/"
    weight = 1

[[main]]
    name = "Social"
    post = ""
    pre = "<i class='fa fa-heart'></i>"
    weight = 4

[[main]]
    name = "YouTube"
    url = "https://youtube.com/channel/UCt4EQeD5QI5pV783lgysgDg"
    hrefTargetBlank = true
    parent = "Social"

[[main]]
    name = "Facebook"
    url = "https://facebook.com/linuxworld45"
    hrefTargetBlank = true
    parent = "Social"
